// Mocks generated by Mockito 5.3.2 from annotations
// in shop_app/test/test/domain/use_cases/add_category_test_use_case.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i10;

import 'package:mockito/mockito.dart' as _i1;
import 'package:shop_app/shop/data/models/category_request_model.dart' as _i11;
import 'package:shop_app/shop/data/models/category_response.dart' as _i2;
import 'package:shop_app/shop/data/models/customer_model.dart' as _i7;
import 'package:shop_app/shop/data/models/dashboard_model.dart' as _i8;
import 'package:shop_app/shop/data/models/order_detail_model.dart' as _i6;
import 'package:shop_app/shop/data/models/order_listing_model.dart' as _i5;
import 'package:shop_app/shop/data/models/product_adding_request.dart' as _i13;
import 'package:shop_app/shop/data/models/product_listing_response.dart' as _i4;
import 'package:shop_app/shop/data/models/product_model.dart' as _i3;
import 'package:shop_app/shop/data/models/requests/customer_request_model.dart'
    as _i18;
import 'package:shop_app/shop/data/models/requests/edit_order_model.dart'
    as _i20;
import 'package:shop_app/shop/data/models/requests/order_status_change.dart'
    as _i19;
import 'package:shop_app/shop/data/models/status_request.dart' as _i17;
import 'package:shop_app/shop/domain/entities/order_entity_request.dart'
    as _i16;
import 'package:shop_app/shop/domain/entities/store_timing_entity.dart' as _i15;
import 'package:shop_app/shop/domain/entities/tag_entity.dart' as _i12;
import 'package:shop_app/shop/domain/entities/unit_entity.dart' as _i14;

import 'add_category_test_use_case.dart' as _i9;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeCategoryResponse_0 extends _i1.SmartFake
    implements _i2.CategoryResponse {
  _FakeCategoryResponse_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeProductModel_1 extends _i1.SmartFake implements _i3.ProductModel {
  _FakeProductModel_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeProductResponse_2 extends _i1.SmartFake
    implements _i4.ProductResponse {
  _FakeProductResponse_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeOrderListModel_3 extends _i1.SmartFake
    implements _i5.OrderListModel {
  _FakeOrderListModel_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeOrderDetailModel_4 extends _i1.SmartFake
    implements _i6.OrderDetailModel {
  _FakeOrderDetailModel_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCustomerListModel_5 extends _i1.SmartFake
    implements _i7.CustomerListModel {
  _FakeCustomerListModel_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDashBoardModel_6 extends _i1.SmartFake
    implements _i8.DashBoardModel {
  _FakeDashBoardModel_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [MockProductRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockMockProductRepository extends _i1.Mock
    implements _i9.MockProductRepository {
  MockMockProductRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i10.Future<_i2.CategoryResponse> getCategories({
    String? searchKey,
    int? page,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCategories,
          [],
          {
            #searchKey: searchKey,
            #page: page,
          },
        ),
        returnValue:
            _i10.Future<_i2.CategoryResponse>.value(_FakeCategoryResponse_0(
          this,
          Invocation.method(
            #getCategories,
            [],
            {
              #searchKey: searchKey,
              #page: page,
            },
          ),
        )),
      ) as _i10.Future<_i2.CategoryResponse>);
  @override
  _i10.Future<_i3.ProductModel> getProductDetails(int? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getProductDetails,
          [id],
        ),
        returnValue: _i10.Future<_i3.ProductModel>.value(_FakeProductModel_1(
          this,
          Invocation.method(
            #getProductDetails,
            [id],
          ),
        )),
      ) as _i10.Future<_i3.ProductModel>);
  @override
  _i10.Future<String> deleteProduct(int? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteProduct,
          [id],
        ),
        returnValue: _i10.Future<String>.value(''),
      ) as _i10.Future<String>);
  @override
  _i10.Future<_i4.ProductResponse> getProducts({
    String? searchKey,
    required int? page,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getProducts,
          [],
          {
            #searchKey: searchKey,
            #page: page,
          },
        ),
        returnValue:
            _i10.Future<_i4.ProductResponse>.value(_FakeProductResponse_2(
          this,
          Invocation.method(
            #getProducts,
            [],
            {
              #searchKey: searchKey,
              #page: page,
            },
          ),
        )),
      ) as _i10.Future<_i4.ProductResponse>);
  @override
  _i10.Future<String> addCategory(_i11.CategoryRequestModel? model) =>
      (super.noSuchMethod(
        Invocation.method(
          #addCategory,
          [model],
        ),
        returnValue: _i10.Future<String>.value(''),
      ) as _i10.Future<String>);
  @override
  _i10.Future<String> updateProductStatus({
    required String? id,
    required int? status,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateProductStatus,
          [],
          {
            #id: id,
            #status: status,
          },
        ),
        returnValue: _i10.Future<String>.value(''),
      ) as _i10.Future<String>);
  @override
  _i10.Future<List<_i12.TagEntity>> getTags() => (super.noSuchMethod(
        Invocation.method(
          #getTags,
          [],
        ),
        returnValue:
            _i10.Future<List<_i12.TagEntity>>.value(<_i12.TagEntity>[]),
      ) as _i10.Future<List<_i12.TagEntity>>);
  @override
  _i10.Future<String> addProducts(_i13.ProductAddingRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #addProducts,
          [request],
        ),
        returnValue: _i10.Future<String>.value(''),
      ) as _i10.Future<String>);
  @override
  _i10.Future<List<_i14.UnitEntity>> getUnits() => (super.noSuchMethod(
        Invocation.method(
          #getUnits,
          [],
        ),
        returnValue:
            _i10.Future<List<_i14.UnitEntity>>.value(<_i14.UnitEntity>[]),
      ) as _i10.Future<List<_i14.UnitEntity>>);
  @override
  _i10.Future<_i2.CategoryResponse> getSubCategories({
    String? searchKey,
    int? page,
    required int? parentId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSubCategories,
          [],
          {
            #searchKey: searchKey,
            #page: page,
            #parentId: parentId,
          },
        ),
        returnValue:
            _i10.Future<_i2.CategoryResponse>.value(_FakeCategoryResponse_0(
          this,
          Invocation.method(
            #getSubCategories,
            [],
            {
              #searchKey: searchKey,
              #page: page,
              #parentId: parentId,
            },
          ),
        )),
      ) as _i10.Future<_i2.CategoryResponse>);
  @override
  _i10.Future<String> deleteCategory(int? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteCategory,
          [id],
        ),
        returnValue: _i10.Future<String>.value(''),
      ) as _i10.Future<String>);
  @override
  _i10.Future<List<_i15.StoreTimingEntity>> getStoreTiming() =>
      (super.noSuchMethod(
        Invocation.method(
          #getStoreTiming,
          [],
        ),
        returnValue: _i10.Future<List<_i15.StoreTimingEntity>>.value(
            <_i15.StoreTimingEntity>[]),
      ) as _i10.Future<List<_i15.StoreTimingEntity>>);
  @override
  _i10.Future<String> updateStoreTiming(
          List<_i15.StoreTimingEntity>? timings) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateStoreTiming,
          [timings],
        ),
        returnValue: _i10.Future<String>.value(''),
      ) as _i10.Future<String>);
  @override
  _i10.Future<String> updateCategoryStatus({
    required String? id,
    required int? status,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateCategoryStatus,
          [],
          {
            #id: id,
            #status: status,
          },
        ),
        returnValue: _i10.Future<String>.value(''),
      ) as _i10.Future<String>);
  @override
  _i10.Future<_i5.OrderListModel> getOrders(_i16.OrderEntityRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #getOrders,
          [request],
        ),
        returnValue:
            _i10.Future<_i5.OrderListModel>.value(_FakeOrderListModel_3(
          this,
          Invocation.method(
            #getOrders,
            [request],
          ),
        )),
      ) as _i10.Future<_i5.OrderListModel>);
  @override
  _i10.Future<_i6.OrderDetailModel> getOrderDetail(int? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getOrderDetail,
          [id],
        ),
        returnValue:
            _i10.Future<_i6.OrderDetailModel>.value(_FakeOrderDetailModel_4(
          this,
          Invocation.method(
            #getOrderDetail,
            [id],
          ),
        )),
      ) as _i10.Future<_i6.OrderDetailModel>);
  @override
  _i10.Future<String> updateStoreOffline(_i17.OfflineStatusRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateStoreOffline,
          [request],
        ),
        returnValue: _i10.Future<String>.value(''),
      ) as _i10.Future<String>);
  @override
  _i10.Future<_i7.CustomerListModel> getCustomer(
          _i18.CustomerRequestModel? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCustomer,
          [request],
        ),
        returnValue:
            _i10.Future<_i7.CustomerListModel>.value(_FakeCustomerListModel_5(
          this,
          Invocation.method(
            #getCustomer,
            [request],
          ),
        )),
      ) as _i10.Future<_i7.CustomerListModel>);
  @override
  _i10.Future<Map<String, dynamic>> changeOrderStatus(
          _i19.OrderStatusChange? model) =>
      (super.noSuchMethod(
        Invocation.method(
          #changeOrderStatus,
          [model],
        ),
        returnValue:
            _i10.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i10.Future<Map<String, dynamic>>);
  @override
  _i10.Future<String> editOrder(_i20.EditOrderDetailModel? model) =>
      (super.noSuchMethod(
        Invocation.method(
          #editOrder,
          [model],
        ),
        returnValue: _i10.Future<String>.value(''),
      ) as _i10.Future<String>);
  @override
  _i10.Future<_i8.DashBoardModel> getDashBoard() => (super.noSuchMethod(
        Invocation.method(
          #getDashBoard,
          [],
        ),
        returnValue:
            _i10.Future<_i8.DashBoardModel>.value(_FakeDashBoardModel_6(
          this,
          Invocation.method(
            #getDashBoard,
            [],
          ),
        )),
      ) as _i10.Future<_i8.DashBoardModel>);
}
