// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAN7E5q-3c0Yg-sW9AhsTrU64XfsOrl9qM',
    appId: '1:761223518670:android:1c9de6ad9677a02bda739f',
    messagingSenderId: '761223518670',
    projectId: 'shop-d9dbb',
    storageBucket: 'shop-d9dbb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmjvf3yKn9A0ovWb_6jLp9zvLKYwPSz40',
    appId: '1:761223518670:ios:91a33d21336ae182da739f',
    messagingSenderId: '761223518670',
    projectId: 'shop-d9dbb',
    storageBucket: 'shop-d9dbb.appspot.com',
    iosBundleId: 'com.fineKube.shopApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOqeu_6sQCcWdyLqeN-oAmBbeKGzn7PT4',
    appId: '1:761223518670:web:cb9d078d2b7777c4da739f',
    messagingSenderId: '761223518670',
    projectId: 'shop-d9dbb',
    authDomain: 'shop-d9dbb.firebaseapp.com',
    storageBucket: 'shop-d9dbb.appspot.com',
    measurementId: 'G-4ZL7SRFFLH',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQchHB0wfh4F6xjx2PdRlmfG3B4rbMlqA',
    appId: '1:103357185550:ios:fbb19aaf19fc384fbec65f',
    messagingSenderId: '103357185550',
    projectId: 'naturebeatz-af459',
    storageBucket: 'naturebeatz-af459.appspot.com',
    iosBundleId: 'com.fineKube.shopAppNew',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDOqeu_6sQCcWdyLqeN-oAmBbeKGzn7PT4',
    appId: '1:761223518670:web:7d2ceb79d8156e61da739f',
    messagingSenderId: '761223518670',
    projectId: 'shop-d9dbb',
    authDomain: 'shop-d9dbb.firebaseapp.com',
    storageBucket: 'shop-d9dbb.appspot.com',
    measurementId: 'G-JDKR8TFBY1',
  );

}